/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WealthShieldRouteImport } from './routes/wealth-shield'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PastFinancesRouteImport } from './routes/past-finances'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FinancialProfileRouteImport } from './routes/financial-profile'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CeptivoRouteImport } from './routes/ceptivo'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PastFinancesIndexRouteImport } from './routes/past-finances.index'
import { Route as PastFinancesIdRouteImport } from './routes/past-finances.$id'
import { Route as BusinessesIdRouteImport } from './routes/businesses.$id'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api.paystack-webhook'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'

const WealthShieldRoute = WealthShieldRouteImport.update({
  id: '/wealth-shield',
  path: '/wealth-shield',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PastFinancesRoute = PastFinancesRouteImport.update({
  id: '/past-finances',
  path: '/past-finances',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialProfileRoute = FinancialProfileRouteImport.update({
  id: '/financial-profile',
  path: '/financial-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CeptivoRoute = CeptivoRouteImport.update({
  id: '/ceptivo',
  path: '/ceptivo',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastFinancesIndexRoute = PastFinancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PastFinancesRoute,
} as any)
const PastFinancesIdRoute = PastFinancesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PastFinancesRoute,
} as any)
const BusinessesIdRoute = BusinessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusinessesRoute,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack-webhook',
  path: '/api/paystack-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof BudgetsRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/ceptivo': typeof CeptivoRoute
  '/clients': typeof ClientsRoute
  '/earnings': typeof EarningsRoute
  '/expenses': typeof ExpensesRoute
  '/financial-profile': typeof FinancialProfileRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/past-finances': typeof PastFinancesRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/premium': typeof PremiumRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wealth-shield': typeof WealthShieldRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/past-finances/$id': typeof PastFinancesIdRoute
  '/past-finances/': typeof PastFinancesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof BudgetsRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/ceptivo': typeof CeptivoRoute
  '/clients': typeof ClientsRoute
  '/earnings': typeof EarningsRoute
  '/expenses': typeof ExpensesRoute
  '/financial-profile': typeof FinancialProfileRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/pipeline': typeof PipelineRoute
  '/premium': typeof PremiumRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wealth-shield': typeof WealthShieldRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/past-finances/$id': typeof PastFinancesIdRoute
  '/past-finances': typeof PastFinancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof BudgetsRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/ceptivo': typeof CeptivoRoute
  '/clients': typeof ClientsRoute
  '/earnings': typeof EarningsRoute
  '/expenses': typeof ExpensesRoute
  '/financial-profile': typeof FinancialProfileRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/past-finances': typeof PastFinancesRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/premium': typeof PremiumRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wealth-shield': typeof WealthShieldRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/past-finances/$id': typeof PastFinancesIdRoute
  '/past-finances/': typeof PastFinancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/auth'
    | '/budgets'
    | '/businesses'
    | '/categories'
    | '/ceptivo'
    | '/clients'
    | '/earnings'
    | '/expenses'
    | '/financial-profile'
    | '/forecast'
    | '/goals'
    | '/investments'
    | '/past-finances'
    | '/pipeline'
    | '/premium'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/wealth-shield'
    | '/accounts/$id'
    | '/api/paystack-webhook'
    | '/businesses/$id'
    | '/past-finances/$id'
    | '/past-finances/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/auth'
    | '/budgets'
    | '/businesses'
    | '/categories'
    | '/ceptivo'
    | '/clients'
    | '/earnings'
    | '/expenses'
    | '/financial-profile'
    | '/forecast'
    | '/goals'
    | '/investments'
    | '/pipeline'
    | '/premium'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/wealth-shield'
    | '/accounts/$id'
    | '/api/paystack-webhook'
    | '/businesses/$id'
    | '/past-finances/$id'
    | '/past-finances'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/analytics'
    | '/auth'
    | '/budgets'
    | '/businesses'
    | '/categories'
    | '/ceptivo'
    | '/clients'
    | '/earnings'
    | '/expenses'
    | '/financial-profile'
    | '/forecast'
    | '/goals'
    | '/investments'
    | '/past-finances'
    | '/pipeline'
    | '/premium'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/wealth-shield'
    | '/accounts/$id'
    | '/api/paystack-webhook'
    | '/businesses/$id'
    | '/past-finances/$id'
    | '/past-finances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BudgetsRoute: typeof BudgetsRoute
  BusinessesRoute: typeof BusinessesRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  CeptivoRoute: typeof CeptivoRoute
  ClientsRoute: typeof ClientsRoute
  EarningsRoute: typeof EarningsRoute
  ExpensesRoute: typeof ExpensesRoute
  FinancialProfileRoute: typeof FinancialProfileRoute
  ForecastRoute: typeof ForecastRoute
  GoalsRoute: typeof GoalsRoute
  InvestmentsRoute: typeof InvestmentsRoute
  PastFinancesRoute: typeof PastFinancesRouteWithChildren
  PipelineRoute: typeof PipelineRoute
  PremiumRoute: typeof PremiumRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  WealthShieldRoute: typeof WealthShieldRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wealth-shield': {
      id: '/wealth-shield'
      path: '/wealth-shield'
      fullPath: '/wealth-shield'
      preLoaderRoute: typeof WealthShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-finances': {
      id: '/past-finances'
      path: '/past-finances'
      fullPath: '/past-finances'
      preLoaderRoute: typeof PastFinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-profile': {
      id: '/financial-profile'
      path: '/financial-profile'
      fullPath: '/financial-profile'
      preLoaderRoute: typeof FinancialProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceptivo': {
      id: '/ceptivo'
      path: '/ceptivo'
      fullPath: '/ceptivo'
      preLoaderRoute: typeof CeptivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-finances/': {
      id: '/past-finances/'
      path: '/'
      fullPath: '/past-finances/'
      preLoaderRoute: typeof PastFinancesIndexRouteImport
      parentRoute: typeof PastFinancesRoute
    }
    '/past-finances/$id': {
      id: '/past-finances/$id'
      path: '/$id'
      fullPath: '/past-finances/$id'
      preLoaderRoute: typeof PastFinancesIdRouteImport
      parentRoute: typeof PastFinancesRoute
    }
    '/businesses/$id': {
      id: '/businesses/$id'
      path: '/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof BusinessesIdRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/api/paystack-webhook': {
      id: '/api/paystack-webhook'
      path: '/api/paystack-webhook'
      fullPath: '/api/paystack-webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsIdRoute: typeof AccountsIdRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsIdRoute: AccountsIdRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface BusinessesRouteChildren {
  BusinessesIdRoute: typeof BusinessesIdRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesIdRoute: BusinessesIdRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

interface PastFinancesRouteChildren {
  PastFinancesIdRoute: typeof PastFinancesIdRoute
  PastFinancesIndexRoute: typeof PastFinancesIndexRoute
}

const PastFinancesRouteChildren: PastFinancesRouteChildren = {
  PastFinancesIdRoute: PastFinancesIdRoute,
  PastFinancesIndexRoute: PastFinancesIndexRoute,
}

const PastFinancesRouteWithChildren = PastFinancesRoute._addFileChildren(
  PastFinancesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BudgetsRoute: BudgetsRoute,
  BusinessesRoute: BusinessesRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  CeptivoRoute: CeptivoRoute,
  ClientsRoute: ClientsRoute,
  EarningsRoute: EarningsRoute,
  ExpensesRoute: ExpensesRoute,
  FinancialProfileRoute: FinancialProfileRoute,
  ForecastRoute: ForecastRoute,
  GoalsRoute: GoalsRoute,
  InvestmentsRoute: InvestmentsRoute,
  PastFinancesRoute: PastFinancesRouteWithChildren,
  PipelineRoute: PipelineRoute,
  PremiumRoute: PremiumRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  WealthShieldRoute: WealthShieldRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
